apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: simulado-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: giropops-cron
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo Simulado Kbernetes - LinuxTips VAIIII
          restartPolicy: OnFailure
