apiVersion: v1
kind: Pod
metadata:
  name: containerport
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    ports:
      - containerPort: 80
    env:
    - name: NGINX_PORT
      value: "8080"
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /giropops
      name: giropops-dir
  volumes:
  - name: giropops-dir
    emptyDir: {}
