apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-limitado
  namespace: constraints-cpu-example
spec:
  limits:
  - max:
      cpu: "800m"
    min:
      cpu: "200m"
    type: Container
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx-limitado
  name: nginx-limitado
  namespace: constraints-cpu-example
spec:
  replicas: 5
  selector:
    matchLabels:
      run: nginx-limitado
  template:
    metadata:
      labels:
        run: nginx-limitado
    spec:
      containers:
      - image: nginx:1.15.0
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      restartPolicy: Always
