apiVersion: v1
kind: Pod
metadata:
  name: customcommand
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    resources:
      limits:
        cpu: "250m"
